[package]
name = "dict_deduplicator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusqlite = "0.28.0"
clap = {version = "4.1.8",features = ["derive"]}
threadpool = "1.8.1"